name: 'Static Checks: Lint Check, Type Check'

on:
  workflow_dispatch:
  pull_request:

jobs:
  static-checks:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    # The `steps` key groups together all the steps that will run as part of the `check-links` job. Each job in a workflow has its own `steps` section.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.0.0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Type check
        run: pnpm typecheck
